import './globals.css';
import type { Metadata } from 'next';
import { Inter } from 'next/font/google';
import { getServerSession } from 'next-auth';
import Link from 'next/link';
import Logout from './logout';

import { ToastContainer } from 'react-toastify';
import 'react-toastify/dist/ReactToastify.css';
import { AddProductButton } from './products/(components)/AddProductButton';
import { Provider } from '@/shared/providers';

const inter = Inter({ subsets: ['latin'] });

export const metadata: Metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
};

export default async function RootLayout({ children }: { children: React.ReactNode }) {
  const session = await getServerSession();

  return (
    <html lang="en">
      <body className={inter.className}>
        <Provider>
          <ToastContainer />
          <nav className="flex mb-8 mt-4 px-3 md:items-end flex-wrap">
            <div className="container">
              {' '}
              <AddProductButton session={session} />
              <Link className="button" href="/products">
                Каталог
              </Link>
            </div>

            <div className="md:ml-auto container mt-3">
              {!!session && <Logout />}
              {!session && (
                <>
                  <Link className="button" href="/login">
                    Войти
                  </Link>

                  <Link className="button" href="/register">
                    Регистрация
                  </Link>
                </>
              )}
            </div>
          </nav>
          {children}
        </Provider>
      </body>
    </html>
  );
}
